project_name: octopus-prometheus

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64

dockers:
- image_templates:
  - "ghcr.io/misguidedemails/{{.ProjectName}}:latest"
  - "ghcr.io/misguidedemails/{{.ProjectName}}:{{.RawVersion}}"
  - "ghcr.io/misguidedemails/{{.ProjectName}}:{{.Major}}.{{.Minor}}"
